version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: apinodejs
      MYSQL_DATABASE: apinodejs
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
